# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cd3999e41e38c0fba7c10b76754222a2f27885b03e0073470aa9d3094da5615915508dea12d2341847d23315b40058c79f0695fcc8eed12fcc1d3e060f88dbc

test:
  secret_key_base: 82b47b08b0e7bf7c70c43f2805a78976f44f21fd8246416330d7868b31e5b9f71a066ed51beb131371a0193d0f457c5d3048dcbcdf506db4d9567075ca92f8b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
